# Generated by Django 2.1.5 on 2026-01-31 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('visibility_status', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('public', 'Public'), ('moderated', 'Moderated')], db_index=True, default='private', max_length=20)),
                ('moderation_reason', models.TextField(blank=True)),
                ('orphaned_from_user', models.CharField(blank=True, help_text='Original owner username if the owner account was deleted.', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
