# Generated by Django 2.1.5 on 2026-02-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_documentattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='moderated_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
