# Generated by Django 6.0.1 on 2026-03-08 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_brightness_userprofile_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
    ]
