# Generated by Django 6.0.1 on 2026-03-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_comment_id_alter_document_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='brightness',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh', '简体中文')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='page_zoom',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='text_size',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tts_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
